name: CD
run-name: running CD workflow 🚀

on:
  push:
    branches:
      - master

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: install npm dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist

  download:
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: download
        uses: actions/download-artifact@v4

      - name: list downloaded artifcat
        run: ls
